[package]
name = "ilattice3"
version = "0.1.0"
authors = ["Duncan Fairbanks <bonsairobo@gmail.com>"]
edition = "2018"

description = "Data types, structures, and algorithms for 3D integer lattices (voxels)"

[features]
default = []

vox = ["dot_vox"]
img = ["image"]

[dependencies]
enum-primitive-derive = "*"
itertools = "*"
num = "*"
num-traits = "*"
serde = { version = "*", features = ["derive"] }

dot_vox = { version = "*", optional = true }
image = { version = "*", optional = true }
